import { Router } from 'express';
import authenticate from '../../middleware/auth.middleware.js';
import authorize from '../../middleware/rbac.middleware.js';
import * as ctrl from './chief-doctor.controller.js';
const router=Router();
router.use(authenticate,authorize('BAS_HEKIM','ADMIN','SUPER_ADMIN'));
router.get('/dashboard',ctrl.dashboard);
router.get('/doctors',ctrl.doctors);
router.get('/departments',ctrl.departments);
router.get('/appointments',ctrl.appointments);
router.patch('/appointments/:id/reassign',ctrl.reassign);
router.get('/laboratory',ctrl.labs);
router.patch('/laboratory/:id/approve',ctrl.approveLab);
router.patch('/laboratory/:id/return',ctrl.returnLab);
router.get('/documents',ctrl.documents);
router.patch('/documents/:kind/:id/review',ctrl.reviewDocument);
router.get('/incidents',ctrl.incidents);
router.post('/incidents',ctrl.createIncident);
router.patch('/incidents/:id',ctrl.updateIncident);
router.get('/councils',ctrl.councils);
router.post('/councils',ctrl.createCouncil);
router.patch('/councils/:id',ctrl.updateCouncil);
router.get('/reports',ctrl.reports);
router.get('/audit',ctrl.audit);
export default router;
