import { useEffect,useMemo,useState } from 'react'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import api from '../../api/axios'
import ChiefDoctorLayout from '../../components/chief-doctor/ChiefDoctorLayout'

const ENDPOINT={dashboard:'dashboard',doctors:'doctors',departments:'departments',appointments:'appointments',laboratory:'laboratory',documents:'documents',councils:'councils',incidents:'incidents',reports:'reports',audit:'audit'}
const pickList=(section,data)=>section==='doctors'?data.items:section==='departments'?data:section==='appointments'?data.items:section==='laboratory'?data.results:section==='documents'?[...(data.ehr||[]).map(x=>({...x,kind:'ehr'})),...(data.discharges||[]).map(x=>({...x,kind:'discharge'})),...(data.certificates||[]).map(x=>({...x,kind:'certificate'}))]:section==='councils'||section==='incidents'||section==='audit'?data.items:[]
const nameOf=x=>x?.userId?.fullName||x?.fullName||x?.patientFullName||x?.name||'—'

export default function ChiefDoctorPage({section}){
 const {t}=useTranslation();const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [search,setSearch]=useState('')
 const load=async()=>{setLoading(true);setError('');try{const r=await api.get(`/chief-doctor/${ENDPOINT[section]}`,{params:search?{search}:undefined});setData(r.data.data)}catch(e){setError(e.response?.data?.message||t('chiefDoctor.error'))}finally{setLoading(false)}}
 useEffect(()=>{const timer=setTimeout(()=>load(),0);return()=>clearTimeout(timer)},[section]) // eslint-disable-line react-hooks/exhaustive-deps
 const rows=useMemo(()=>pickList(section,data||{}),[section,data])
 const act=async(path,body,confirmKey)=>{if(confirmKey&&!window.confirm(t(confirmKey)))return;try{await api.patch(path,body);toast.success(t('chiefDoctor.saved'));load()}catch(e){toast.error(e.response?.data?.message||t('chiefDoctor.error'))}}
 const promptAction=(label,path,bodyKey='reason')=>{const value=window.prompt(t(label));if(value?.trim())act(path,{[bodyKey]:value.trim()})}
 const createCouncil=async()=>{const patientId=window.prompt(t('chiefDoctor.fields.patientId'));const title=window.prompt(t('chiefDoctor.fields.title'));const clinicalReason=window.prompt(t('chiefDoctor.fields.reason'));if(!patientId||!title||!clinicalReason)return;try{await api.post('/chief-doctor/councils',{patientId,title,clinicalReason});toast.success(t('chiefDoctor.saved'));load()}catch(e){toast.error(e.response?.data?.message||t('chiefDoctor.error'))}}
 const createIncident=async()=>{const patientId=window.prompt(t('chiefDoctor.fields.patientId'));const title=window.prompt(t('chiefDoctor.fields.title'));if(!patientId||!title)return;try{await api.post('/chief-doctor/incidents',{patientId,title,type:'other',priority:'high'});toast.success(t('chiefDoctor.saved'));load()}catch(e){toast.error(e.response?.data?.message||t('chiefDoctor.error'))}}
 return <ChiefDoctorLayout><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',marginBottom:20,flexWrap:'wrap'}}><div><h1 style={{margin:0,fontSize:22,color:'#071B2E'}}>{t(`chiefDoctor.nav.${section}`)}</h1><p style={{margin:'4px 0 0',fontSize:13,color:'#64748b'}}>{t(`chiefDoctor.descriptions.${section}`)}</p></div><div style={{display:'flex',gap:8}}>{['doctors','appointments','laboratory'].includes(section)&&<><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={t('chiefDoctor.search')} style={{border:'1px solid #dce5ec',borderRadius:8,padding:'9px 12px'}}/><button onClick={load} style={btn}>{t('chiefDoctor.filter')}</button></>}{section==='councils'&&<button onClick={createCouncil} style={btn}>{t('chiefDoctor.create')}</button>}{section==='incidents'&&<button onClick={createIncident} style={btn}>{t('chiefDoctor.create')}</button>}</div></div>
 {loading?<State text={t('chiefDoctor.loading')}/>:error?<State text={error} error/>:section==='dashboard'?<Dashboard data={data} t={t}/>:section==='reports'?<Reports data={data} t={t}/>:rows.length===0?<State text={t('chiefDoctor.empty')}/>:<div style={{display:'grid',gap:10}}>{rows.map((x,i)=><Row key={x._id||i} section={section} x={x} t={t} act={act} promptAction={promptAction}/>)}</div>}
 </ChiefDoctorLayout>
}
const btn={border:0,borderRadius:8,padding:'9px 14px',background:'#168C96',color:'white',fontWeight:600,cursor:'pointer'}
function State({text,error}){return <div style={{padding:36,textAlign:'center',background:'white',border:'1px solid #e2e8f0',borderRadius:12,color:error?'#b91c1c':'#64748b'}}>{text}</div>}
function Dashboard({data,t}){const s=data?.stats||{};return <><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(160px,1fr))',gap:12,marginBottom:18}}>{Object.entries(s).map(([k,v])=><div key={k} style={card}><div style={{fontSize:12,color:'#64748b'}}>{t(`chiefDoctor.stats.${k}`)}</div><div style={{fontSize:25,fontWeight:800,color:'#071B2E',marginTop:5}}>{v}</div></div>)}</div><div style={card}><h3>{t('chiefDoctor.todayFlow')}</h3>{(data?.appointments||[]).map(a=><div key={a._id} style={line}>{a.startTime} · {nameOf(a.patientId)} · {nameOf(a.doctorId)}</div>)}</div></>}
function Reports({data,t}){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:12}}><div style={card}><h3>{t('chiefDoctor.reportAppointments')}</h3>{(data?.appointmentsByStatus||[]).map(x=><div style={line} key={x._id}>{x._id}: {x.count}</div>)}</div><div style={card}><h3>{t('chiefDoctor.reportClinical')}</h3><div style={line}>{t('chiefDoctor.labHours')}: {Number(data?.averageLabApprovalHours||0).toFixed(1)}</div><div style={line}>{t('chiefDoctor.approvedDocuments')}: {data?.approvedDocuments||0}</div></div></div>}
function Row({section,x,t,act,promptAction}){const patient=nameOf(x.patientId);const doctor=nameOf(x.doctorId||x.responsibleDoctorId||x.dischargingDoctor);return <div style={{...card,display:'flex',gap:12,justifyContent:'space-between',alignItems:'center',flexWrap:'wrap'}}><div style={{minWidth:0}}><div style={{fontWeight:700,color:'#071B2E'}}>{x.title||x.protocolNo||nameOf(x.userId)||x.name||patient}</div><div style={{fontSize:12,color:'#64748b',marginTop:4}}>{[patient,doctor,x.status,x.priority,x.departmentName,x.specialization].filter(v=>v&&v!=='—').join(' · ')}</div></div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{section==='laboratory'&&x.status==='completed'&&<><button style={btn} onClick={()=>act(`/chief-doctor/laboratory/${x._id}/approve`,{},'chiefDoctor.confirmApprove')}>{t('chiefDoctor.approve')}</button><button style={danger} onClick={()=>promptAction('chiefDoctor.returnReason',`/chief-doctor/laboratory/${x._id}/return`)}>{t('chiefDoctor.return')}</button></>}{section==='documents'&&x.approvalStatus==='submitted'&&<><button style={btn} onClick={()=>act(`/chief-doctor/documents/${x.kind}/${x._id}/review`,{action:'approve'},'chiefDoctor.confirmApprove')}>{t('chiefDoctor.approve')}</button><button style={danger} onClick={()=>{const reason=window.prompt(t('chiefDoctor.returnReason'));if(reason)act(`/chief-doctor/documents/${x.kind}/${x._id}/review`,{action:'return',reason})}}>{t('chiefDoctor.return')}</button></>}{section==='incidents'&&x.status!=='resolved'&&<button style={btn} onClick={()=>act(`/chief-doctor/incidents/${x._id}`,{status:'resolved'},'chiefDoctor.confirmResolve')}>{t('chiefDoctor.resolve')}</button>}{section==='councils'&&x.status!=='completed'&&<button style={btn} onClick={()=>{const finalDecision=window.prompt(t('chiefDoctor.finalDecision'));if(finalDecision)act(`/chief-doctor/councils/${x._id}`,{finalDecision})}}>{t('chiefDoctor.complete')}</button>}{section==='appointments'&&<button style={btn} onClick={()=>{const doctorId=window.prompt(t('chiefDoctor.fields.doctorId'));const reason=window.prompt(t('chiefDoctor.fields.reason'));if(doctorId&&reason)act(`/chief-doctor/appointments/${x._id}/reassign`,{doctorId,reason})}}>{t('chiefDoctor.reassign')}</button>}</div></div>}
const card={background:'white',border:'1px solid #e2e8f0',borderRadius:12,padding:16,boxShadow:'0 2px 8px rgba(15,23,42,.03)'}
const line={padding:'8px 0',borderBottom:'1px solid #f1f5f9',fontSize:13,color:'#475569'}
const danger={...btn,background:'#b91c1c'}
